### ISSUE TITLE
zou je alsnog kunnen doen

### ISSUE THREAD

**Issue by Theo-denBlanken** [eniciodehaas/pixel-perfext-sass#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
//OEFENEN MET DARKEN EN LIGHTEN, WORDEN NIET GEBRUIKT

$donkerder: darken($hoofdkleur, 20%)

$lichter: lighten($hoofdkleur, 20%) 
```

URL: https://github.com/eniciodehaas/pixel-perfext-sass/blob/master/scss/_vars.sass

Feedback: bij de ipad-actie[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"0d75b64e7431766cf45944f0ef7b4986d3f5e6ff","path":"scss/_vars.sass","reviewer":"Theo-denBlanken"}')

**Comment by eniciodehaas** [comment]
het ipad-winactie blok heeft een 'lighten' background color
