### ISSUE TITLE
Ook hier zou je met darken aan de slag kunnen

### ISSUE THREAD

**Issue by Theo-denBlanken** [eniciodehaas/pixel-perfext-sass#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/eniciodehaas/pixel-perfext-sass/blob/master/scss/_nav.sass

Feedback: bijvoorbeeld met een hover[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"8140159afcba52088a93771e2c3f5e84e22c8061","path":"scss/_nav.sass","reviewer":"Theo-denBlanken"}')

**Comment by eniciodehaas** [comment]
Buttons hebben een hover met een 'darken' background
